### ISSUE TITLE
Build is failing because of asset file size

### ISSUE THREAD

**Issue by MCMic** [Larpon/DeadAscend#3]
Hello, attempting at building the game on ArchLinux, I get an error "virtual memory exhausted: Ne peut allouer de la mémoire".

Haiku people had the same one and solved it by splitting the assets in several files, as you can see here: https://github.com/haikuports/haikuports/blob/f92cae670d78574271e067d34d89581839dc03a4/games-rpg/dead_ascend/patches/dead_ascend-1.1.0.patchset

Could you merge this so that the game is easier to build without huge RAM or swap file?

**Comment by larpon** [comment]
@MCMic - wow - didn't know it was getting packaged :-o
That's awesome!
In my new game I've made a separate qmake make target - that runs `rcc` on the command line and build an external `assets.rcc` that gets detected and loaded at runtime - this is *way faster* let alone more memory efficient than compiling it all into the binary - will an extra make target (`make assets`) be a problem you think?

**Comment by larpon** [comment]
Woops. Wrong button

**Comment by MCMic** [comment]
No I don’t think an extra make target would be a problem. I can test it if you push it to a branch.
I’m not used to QML…

If there are commands to build and install the game packaging to ArchLinux should be easy ^^
You can look at what I did for FreeSiege for instance: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=freesiege
I expect Dead Ascend to be about the same steps but with qmake instead of cmake.

**Comment by larpon** [comment]
@MCMic you should be able to build it more efficiently now by running something like
```
qmake DeadAscend.pro
make assets # <- Note this extra step
make
```

**Comment by MCMic** [comment]
I’m failing to use this. It says «make: *** Aucune règle pour fabriquer la cible « assets ». Arrêt.» (it cannot find assets target)

I tried deleting Makefile and running qmake with option «-nocache» without any success. qmake does not give any output so it’s not helpful, not sure what I’m doing wrong.

**Comment by akien-mga** [comment]
The `assets` target is only defined in `App/Makefile`, so you need to run `make assets -C App`.

**Comment by MCMic** [comment]
@akien-mga Thanks that works.
But it seems make install does not support the DESTDIR option so it cannot be used for packaging. (+ it tries to install in /opt it seems instead of /usr/share/…)

**Comment by akien-mga** [comment]
See #4 for a clarification on build instructions.

**Comment by akien-mga** [comment]
With QMake-based projects you should use `INSTALL_ROOT` instead of `DESTDIR`. But yes, the install instructions are not packaging-friendly yet, it will only install the binary without the assets and into `/opt` instead of `/usr/bin` or `/usr/games`.

**Comment by akien-mga** [comment]
@MCMic See #7 for further discussion of Linux packaging.

**Comment by MCMic** [comment]
assets.rcc does not get built.
I think it’s because the target is named assets and there is a folder named assets in App and make thinks it’s the target.
If I rename the target from assets to assets.rcc and run «make assets.rcc» it works.

Also make install should install assets.rcc as well (but see #7 about installation process)

**Comment by akien-mga** [comment]
@MCMic See #5, that's fixed already :)

**Comment by MCMic** [comment]
Oh, ok, sorry for the noise
