### ISSUE TITLE
Add install target for Linux distros

### ISSUE THREAD

**Issue by akien-mga** [Larpon/DeadAscend#7]
Currently the `DeadAscend` binary expects to find its `assets.rcc` file next to the binary: https://github.com/Larpon/DeadAscend/blob/c46ee46e37b3a1b85cfbc77b1fcf959546285634/App/main.cpp#L70

This is practical when running from the source folder, or when shipping pre-compiled versions of the game in a zip/tarball, so this logic should stay, but it should be extended to allow reading assets from a system-specific binary.

On Linux, packagers would typically package games in:
- Either `/usr/bin/deadascend` for the binary (or `/usr/bin/DeadAscend` if they don't have a strict lowercase-only policy) and `/usr/share/deadascend/` for the architecture-independent data (Fedora, openSUSE, Arch, etc.),
- Or `/usr/games/deadascend` for the binary and `/usr/share/games/deadascend` for the architecture-independent data (Debian, Ubuntu, Mageia, etc.)

Regardless of whether the games-specific FHS paths are used by the distro, it's a strong requirement that data and binary are not packaged together, so the binary should be able to find its data in that other path.

A simple way to ensure it is to give packagers command line options to define said path, e.g. `qmake bindir=/usr/games datadir=/usr/share/games/deadascend`. Alternatively, you can hardcore looking in both `/usr/share/<name>/` and `/usr/share/games/<name>/` for the game's data before defaulting to the binary dir.

**Comment by MCMic** [comment]
Please do not hardcode anything.
People like to install to /usr/local when they install by hand, or sometime /opt, while packagers will need to put in /usr/share/….

**Comment by akien-mga** [comment]
Well *something* has to be hardcoded. Whether a lookup map for standard paths or a user-defined `DATADIR`, it ends up hardcoded as a define.

**Comment by akien-mga** [comment]
But yeah, the simplest and cleanest way is what I described first, to hardcode a path that can be defined by the user (and if not, a meaningful default value, like `$prefix + /share/`). The installation paths should then match the hardcoded data path of course, so that `make install` puts the assets where the binary expects them.

**Comment by MCMic** [comment]
@akien-mga Define does not stand as hardcoded for me, otherwise all vars with a default value would count as hardcoded :-)

+1 for using $prefix/share and $prefix/bin, it’s the most common thing I’ve seen and it’s quite useful.

**Comment by larpon** [comment]
@akien-mga @MCMic Thanks for your input and help!
I'm not an expert in build systems, let alone linux distro standards.
With commit 67885c819544ca5646e2b236f906f73269c991a8 I can successfully build and run from commandline with this:
```
qmake DeadAscend.pro "BIN_DIR=/tmp/deadascend" "ASSETS_DIR=/tmp/deadascend-data"
make qmake_all # For some reason the "App" dir is not created if I don't run this?
make assets -C App
make -C App
make install
```
I'd like to know how I can omit the `-C` option flag if any of you should know.
Hope it works!
